### ISSUE TITLE
Example SDPs need to use CRLF

### ISSUE THREAD

**Issue by kierank** [AMWA-TV/sdpoker#16]
As per RFC 8866, CRLF is what ends a line yet examples have LF only.

**Comment by garethsb** [comment]
The files in _examples_ directory? They're probably committed as text files, so what you gets depends on platform.

I agree ideally they should check out with CRLF on all platforms.

Though as per RFC 4566, "parsers SHOULD be tolerant and also accept records terminated with a single newline character."

**Comment by kierank** [comment]
I did a wget from the "Raw" tab of GitHub but yes I'm not sure if it does
any processing.

Kieran

**Comment by garethsb** [comment]
Should be resolved by #18 on new clones.
