### ISSUE TITLE
Relax checking of a=fmtp line ending

### ISSUE THREAD

**Issue by andrewbonney** [AMWA-TV/sdpoker#2]
Currently the a=fmtp line is checked for a tailing `; `. This is only necessary because of an inclusion in ST.2110-10. Generic SDP files should not fail because of this, and as this requirement may be revised in ST.2110's one year review it seems unnecessary to penalise implementations for the error.

**Comment by garethsb-sony** [comment]
Right. The latest draft of ST 2110-20 that I've seen:

```patch
 The <format specific parameters> section shall consist of a
 sequence of media type parameter entries, each
-followed by a semicolon (";") character followed by whitespace.
+separated by the semicolon (";") character followed by whitespace.
+There is no semicolon character after the last item. 
```

Do we think that it ought to be revised to say "There is no requirement for a semicolon character after the last item" so that we don't have to start failing all the current implementations that conform to ST 2110-10:2017?

**Comment by andrewbonney** [comment]
Ah yes, as it's fmtp related it was more likely to be in -20.

I suspect there's a danger that if the revised standard provides a grey area it's the usual issue of 'SHOULD' being interpreted as 'MAY'. It may just be that this check generates a warning rather than an error, with an indication of why in the text. As usual, whatever the standard says, receivers *should...* be permissive.
