### ISSUE TITLE
fmtp value check

### ISSUE THREAD

**Issue by Strahlemann** [AMWA-TV/sdpoker#40]
As to my interpretation of the SMPTE ST 2110 suite, fmtp parameters are only required in 2110-20 but not in 2110-30 nor 2110-40, whereas sdpoker makes them mandatory for all SDPs (e.g., raises an error if it's missing).

The proposal would be to parse if m!=audio or if a!= smpte291.
Only then, raise that the fmtp parameter is missing.

**Comment by garethsb** [comment]
The repo contains example files for ST 2110-20, -30, -40, etc. The examples for -30 and -40 do not have `fmtp` attribute, and sdpoker does not report any errors for these files:

```sh
$ node sdpoker.js examples/st2110-30.sdp

$ node sdpoker.js examples/st2110-40.sdp
```

Please explain the issue you are having in more detail.
